### ISSUE TITLE
Compilation errors with Scala 1.12.0-M4

### ISSUE THREAD

**Issue by rickynils** [rickynils/scalacheck#230]
Compiling ScalaCheck 1.13.0 with Scala 1.12.0-M4 results in a lot of errors like these:

```
[error] src/main/scala/org/scalacheck/Cogen.scala:25: missing parameter type
[error]     Cogen((seed, s) => perturb(seed, f(s)))
[error]            ^
[error] src/main/scala/org/scalacheck/Cogen.scala:25: missing parameter type
[error]     Cogen((seed, s) => perturb(seed, f(s)))
```

These errors are introduced by M4, compilation with M3 works fine. Additionally, M4 works fine with ScalaCheck 1.11 and 1.12.

**Comment by dwijnand** [comment]
Ouch. The 2.12.x community build has scalacheck pinned at 1.11.6: https://github.com/scala/community-builds/blame/2.12.x/common.conf#L66

**Comment by xuwei-k** [comment]
`Cogen` is SAM (single abstract method) type, and there are some overload methods.

```scala
def apply[T](implicit ev: Cogen[T]): Cogen[T] = ev

def apply[T](f: (Seed, T) => Seed): Cogen[T] = 
```

https://github.com/rickynils/scalacheck/blob/1.13.0/src/main/scala/org/scalacheck/Cogen.scala

**Comment by xuwei-k** [comment]
similar discussion? https://github.com/scala/scala/pull/4971#issuecomment-202977627

**Comment by SethTisue** [comment]
attn @adriaanm, here's another example of overloading trouble involving SAM support

**Comment by adriaanm** [comment]
That's a fun one! The smallest source-compatible hack I can think of is `def apply[T](implicit ev1: Cogen[T], ev2: Cogen[T]): Cogen[T] = ev1`... Don't tell anyone I recommended that, though :sunglasses: 

Sadly, I don't see how we can improve overload resolution to fix this without pushing it over the complexity brink that it's teetering.

**Comment by rickynils** [comment]
@adriaanm So ScalaCheck follows its tradition of torturing scalac... The workaround works, but I guess I must either bump the ScalaCheck version or create a separate branch for M4.

**Comment by sjrd** [comment]
You can make it both source-compatible and binary compatible like this:
```scala
// binary compatible
private[enclosingpackage] def apply[T](ev: Cogen[T]): Cogen[T] = ev
// source compatible
def apply[T](implicit ev: Cogen[T], dummy: DummyImplicit): Cogen[T] = ev
```

**Comment by rickynils** [comment]
I've implemented the workaround so master now builds with Scala 2.12.0-M4. I've also released a new version of ScalaCheck (1.13.1, both JVM and JS versions), built with Scala 2.10, 2.11 and 2.12-M4.
