### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/Right  when using Scala 2.10 rc2

### ISSUE THREAD

**Issue by hejfelix** [rickynils/scalacheck#40]
Hello,

After switching to Scala 2.10 (due to need for TypeTags) I get the following error:

java.lang.NoClassDefFoundError: scala/Right
    at org.scalacheck.Prop$.forAllShrink(Prop.scala:542)....

Can I make this work with 2.10?
